/*
 * Prebuild step (see CLAUDE.md "BRAT Compatibility").
 *
 * BRAT only distributes manifest.json, main.js and styles.css. The Python
 * backend therefore cannot ship as separate files — it must be bundled into
 * main.js. This script reads every file in backend/ and emits
 * src/backend-embed.ts with the raw sources as exported string constants.
 * main.ts extracts these to disk on first activation.
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const backendDir = join(root, "backend");
const outFile = join(root, "src", "backend-embed.ts");

// Only embed source/text files the backend needs at runtime.
const ALLOWED_EXT = [".py", ".txt"];

function collect(dir, baseDir = dir) {
  const entries = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      if (name === "__pycache__") continue;
      entries.push(...collect(full, baseDir));
    } else if (ALLOWED_EXT.some((ext) => name.endsWith(ext))) {
      // Use POSIX-style relative key so it works as a path on all platforms.
      const rel = full.slice(baseDir.length + 1).split("\\").join("/");
      entries.push([rel, readFileSync(full, "utf8")]);
    }
  }
  return entries;
}

// Escape for a JS template literal: backslashes, backticks, and ${ sequences.
function escapeTemplate(src) {
  return src
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

const files = collect(backendDir).sort((a, b) => a[0].localeCompare(b[0]));

if (files.length === 0) {
  console.error("[embed-backend] no backend files found in", backendDir);
  process.exit(1);
}

const body = files
  .map(([name, content]) => `  ${JSON.stringify(name)}: \`${escapeTemplate(content)}\`,`)
  .join("\n");

const out = `// src/backend-embed.ts — AUTO-GENERATED by scripts/embed-backend.mjs, do not edit.
// Regenerated on every build. Keep out of version control (see .gitignore).

export const BACKEND_FILES: Record<string, string> = {
${body}
};
`;

writeFileSync(outFile, out, "utf8");
console.log(
  `[embed-backend] wrote ${outFile} with ${files.length} file(s): ${files.map((f) => f[0]).join(", ")}`,
);
